server.port=8080

groq.api.key=${GROQ_API_KEY:your_api_key_here}
groq.api.url=https://api.groq.com/openai/v1/chat/completions

spring.data.redis.host=${host_ip_address}
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:your_redis_password_here}